require 'open-uri'

class GamesController < ApplicationController
  def new
    @letters = ("A".."Z").to_a.sample(10)
  end

  def score
    # We retrieve the word
    @word = params[:answer].upcase
    # We retrieve the letters generated by the server
    @grid = params[:letters].split(" ")
    # Check if the word is in the grid (letters)
    if word_is_in_grid?(@word, @grid)
      if english_word?(@word)
        @message = "Congratulations! #{@word} is an english word!"
      else
        @message = "#{@word} is not an english word!"
      end
    else
      @message = "#{@word} is not in the grid!"
    end
  end

  private

  def word_is_in_grid?(word, grid)
    word.chars.all? do |letter|
      grid.count(letter) >= word.count(letter)
    end
  end

  def english_word?(word)
    response = URI.open("https://dictionary.lewagon.com/#{word}").read
    result = JSON.parse(response)
    result["found"]
  end
end
